# Generated by Django 5.1.3 on 2024-12-03 05:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_type', models.CharField(choices=[('country', 'Country'), ('state', 'State'), ('city', 'City')], default='city', max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('state_abbr', models.CharField(blank=True, max_length=3, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='location.location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
